#!/bin/bash

# This script allows group membership in gitolite to be "primed" from
# unix groups.  Add
#
#   GROUPLIST_PGM           =>  '/path/to/gitolite/src/unix-groups',
#
# to your rc file.
#
# Eg. Suppose your gitolite username is "myuser", and it has an unix
# account on the host machine (ie. an /etc/passwd entry, or is in
# ldap, or whatever).  If your unix user is in the groups "group1",
# "group2" and "group3", then using this script and the above
# configuration is equivalent to having in the conf file:
#
# @group1 = myuser
# @group2 = myuser
# @group3 = myuser
#


case "$1" in
	"")
		exit 1
		;;
	gitweb|daemon)
		exit 0
		;;
esac

groups=($(/usr/bin/groups "$1" 2>/dev/null))

# Old versions of coreutils (like 8.4 in Centos 5/6) will always output
# the "username : " prefix, even if only one username is specified.
# Newer versions of coreutils (like 8.15) will only print this prefix if
# more than one user is specified.
# So we should deal with the presence or absence of this prefix.
# At least we don't have to deal with more than one line.
if [ "${groups[0]}" = "$1" -a "${groups[1]}" = ":" ]; then
	groups="${groups[*]:2}"
fi

# FIXME: logging

echo "${groups[*]}"

